spring:
  security:
    user:
      name: tiago.lima
      password: password
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true